services:
  kittycam-server:
    build: .
    ports:
      - "8000:8000"
    devices:
      - /dev/video0:/dev/video0

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped

    command: tunnel run

    volumes:
      - ./cloudflared:/etc/cloudflared

    depends_on:
      - kittycam-server