tunnel: 33297d27-e3b1-49f7-80f0-d12d3f917d69

credentials-file: /etc/cloudflared/33297d27-e3b1-49f7-80f0-d12d3f917d69.json

ingress:
  - hostname: kittycam.kyleesk9s.com
    service: http://kittycam-server:8000

  - service: http_status:404